spring:
  application:
    name: customer-service
  datasource:
    url: jdbc:postgresql://localhost:5432/customerhomework_tb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true
server:
  port: 8083